// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"EventReSpawn","status":true,"description":"イベント動的生成プラグイン","parameters":{"keepSelfSwitch":"false","tryRandomCount":"1000"}}
];
